spring:
  application:
    name: 'pet-service'
  cloud:
    consul:
      config:
        enabled: true
      host: localhost
      port: 8500
      ribbon:
        enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
